baseurl = "https://johnnewbery.com/"
languageCode = "en-us"
title = "John Newbery"
theme = "hugo-type-theme"
# Posts per page
paginate = 10
themesDir = "themes"

[params]
	author = "John Newbery"
	description = "John Newbery's blog, mostly about Bitcoin"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = "Bitcoin"
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/avatar.jpg"

	headerText = "I'm an Bitcoin protocol developer. I contribute to Bitcoin Core and other open source Bitcoin projects."
	# To add a header background to the main site, save your image under static/img/.
	# If no image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"

	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		github = "jnewbery"
		linkedin = "johnnewbery"
		twitter = "jfnewbery"
